version: '3'
services:

  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ~/data:/var/lib/postgresql/data
      - ./migrations/2023-07-04-082332_init/up.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      - db
