version: '3'
services:

  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - /pgdata:/var/lib/postgresql/data
      - ./migrations/2023-07-04-082332_init/up.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: redisserver
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    links:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl-certs/certificate.crt:/etc/nginx/ssl-certs/certificate.cert
      - ./nginx/ssl-certs/key.pem:/etc/nginx/ssl-certs/key.pem

volumes:
  redis-data:
